Repository EFREi-Renforcement-Js-groupe-TDA/MyCvApi, pull requests merged in 2024-10, with the labels that each got.

#5 Slight code and file reorganization
  src/app.js
  src/controller/AuthenticationController.js
  src/controller/UserController.js
  src/models/Role.js
  src/routes/AuthenticationRouter.js
  src/routes/UserRouter.js
  src/routes/auth.js
  src/routes/index.js
  src/validator/UserValidator.js
Labels: documentation, enhancement

#6 Added show endpoint for User
  src/controller/UserController.js
  src/routes/UserRouter.js
  src/utils/Security/SecurityHelper.js
Labels: enhancement

#8 Implements CV
  package-lock.json
  package.json
  src/controller/CvController.js
  src/controller/UserController.js
  src/models/Cv.js
  src/models/User.js
  src/routes/CvRouter.js
  src/routes/index.js
  src/validator/CvValidator.js
Labels: enhancement

#9 CV Hotfix
  src/controller/CvController.js
  src/controller/UserController.js
  src/models/Cv.js
  src/models/User.js
  src/routes/CvRouter.js
  src/validator/CvValidator.js
Labels: bug
